import React, { createContext, useContext, useState, useEffect } from 'react';

/** All supported language codes */
export type SupportedLanguage = 'he' | 'en' | 'fr' | 'es' | 'ru';

/** All valid translation keys (derived from the Hebrew translations object) */
export type TranslationKey = keyof typeof translations['he'];

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

export const translations = {
  he: {
    // Header
    home: 'דף הבית',
    store: 'חנות',
    about: 'אודות', 
    contact: 'צור קשר',
    magazine: 'המגזין',
    join: 'הצטרפות',
    downloads: 'הורדות',
    fire: '🔥 האש שלי',
    discoverCollection: 'גלה אוסף',
    booksAvailable: 'ספרים זמינים',

    // Downloads page
    freeDownloads: 'הורדות חינמיות',
    downloadDescription: 'הורדו ספרי ברסלב במגוון שפות - כל הספרים זמינים בחינם לקהילה',
    search: 'חיפוש',
    searchBooks: 'חפש ספרים...',
    category: 'קטגוריה',
    rebbeNachman: 'כתבי רבי נחמן',
    rebbeNathan: 'כתבי רבי נתן',
    compilations: 'ליקוטים וקבצים',
    downloadLanguage: 'שפת הורדה',
    allLanguages: 'כל השפות',
    availableLanguages: 'שפות זמינות',
    noResultsFound: 'לא נמצאו תוצאות',
    tryDifferentSearch: 'נסה מונחי חיפוש אחרים',
    importantNote: 'הערה חשובה',
    freeDownloadNote: 'כל הספרים זמינים להורדה חינמית לפי רוח הברסלב - התורה שלמה תהיה חינם',

    // Store page
    storeTitle: 'ספרי ברסלב - קרן רבי ישראל',
    storeSubtitle: 'אוסף מקיף של ספרי רבי נחמן מברסלב ותלמידיו במחירים מיוחדים',
    filterBy: 'סינון לפי..',
    freeSearch: 'חיפוש חופשי',
    searchPlaceholder: 'חיפוש...',
    showResults: 'הצג תוצאות חיפוש',
    categories: 'קטגוריות',
    allCategories: 'כל הקטגוריות',
    editionType: 'סוג מהדורה',
    pocketEditions: 'מהדורות כיס',
    luxuryEditions: 'מהדורות יוקרה',
    completeSets: 'סטים מלאים',
    illustratedEditions: 'מהדורות מאוירות',
    leatherBinding: 'כריכת עור',
    languages: 'שפות',
    hebrew: 'עברית',
    english: 'אנגלית',
    french: 'צרפתית',
    russian: 'רוסית',
    spanish: 'ספרדית',
    priceRange: 'טווח מחירים',
    minimum: 'מינימום',
    maximum: 'מקסימום',
    viewProduct: 'צפה במוצר',
    addToCart: 'הוסף לסל',
    freeShipping: 'מחיר כולל משלוח לכל הארץ',
    moreProducts: 'עוד מוצרים זמינים - לקטלוג המלא',
    contactForMore: 'צור קשר לפרטים נוספים',
    ratedOutOf: 'דורג 5.00 מתוך 5',
    options: 'אפשרויות',

    // Checkout page
    checkoutTitle: 'השלמת הזמנה',
    shippingDetails: 'פרטי משלוח',
    fillShippingDetails: 'אנא מלא את פרטי המשלוח שלך',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    email: 'אימייל',
    phone: 'טלפון',
    address: 'כתובת',
    city: 'עיר',
    zipCode: 'מיקוד',
    orderNotes: 'הערות להזמנה',
    orderNotesPlaceholder: 'הערות מיוחדות להזמנה (אופציונלי)',
    orderSummary: 'סיכום הזמנה',
    items: 'פריטים',
    quantity: 'כמות',
    subtotal: 'סכום ביניים',
    shipping: 'משלוח',
    freeShippingLabel: 'חינם',
    subscriberDiscount: 'הנחת מנוי (5%)',
    total: 'סה"כ לתשלום',
    paymentMethod: 'אמצעי תשלום',
    creditCard: 'כרטיס אשראי',
    bit: 'ביט',
    paypal: 'PayPal',
    payNow: 'שלם עכשיו',
    processing: 'מעבד תשלום...',
    emptyCart: 'העגלה שלך ריקה',
    emptyCartDesc: 'הוסף מוצרים לעגלה כדי להמשיך לקופה',
    continueShopping: 'המשך קניות',
    securePayment: 'תשלום מאובטח',
    securePaymentDesc: 'כל הפרטים מוצפנים ומאובטחים',
    firstNameRequired: 'שם פרטי הוא שדה חובה',
    lastNameRequired: 'שם משפחה הוא שדה חובה',
    emailRequired: 'אימייל הוא שדה חובה',
    emailInvalid: 'כתובת אימייל לא תקינה',
    phoneRequired: 'טלפון הוא שדה חובה',
    phoneInvalid: 'מספר טלפון לא תקין (05X-XXXXXXX)',
    addressRequired: 'כתובת היא שדה חובה',
    cityRequired: 'עיר היא שדה חובה',
    zipCodeRequired: 'מיקוד הוא שדה חובה',
    spiritualSupport: 'תמיכה רוחנית',
    spiritualSupportDesc: 'כל רכישה תומכת במשימה הרוחנית של הפצת תורת רבי נחמן מברסלב בכל העולם',
    shippingPolicy: 'מדיניות משלוח והחזרות',
    freeShippingOver: 'משלוח חינם על הזמנות מעל',
    deliveryTime: 'זמן משלוח: 3-7 ימי עסקים',
    returnPolicy: 'החזרה תוך 14 יום מקבלת המוצר',
    defectivePolicy: 'מוצר פגום - החלפה מיידית ללא עלות',

    // Common
    shekel: '₪',
    loading: 'טוען...',
    error: 'שגיאה',
    success: 'הצלחה'
  },
  en: {
    // Header
    home: 'Home',
    store: 'Store',
    about: 'About',
    contact: 'Contact',
    magazine: 'Magazine', 
    join: 'Join',
    downloads: 'Downloads',
    fire: '🔥 My Fire',
    discoverCollection: 'Discover Collection',
    booksAvailable: 'Books Available',

    // Store page
    storeTitle: 'Breslov Books - Rabbi Israel Foundation',
    storeSubtitle: 'Comprehensive collection of Rabbi Nachman of Breslov and his students\' books at special prices',
    filterBy: 'Filter by..',
    freeSearch: 'Free search',
    searchPlaceholder: 'Search...',
    showResults: 'Show search results',
    categories: 'Categories',
    allCategories: 'All categories',
    editionType: 'Edition type',
    pocketEditions: 'Pocket editions',
    luxuryEditions: 'Luxury editions',
    completeSets: 'Complete sets',
    illustratedEditions: 'Illustrated editions',
    leatherBinding: 'Leather binding',
    languages: 'Languages',
    hebrew: 'Hebrew',
    english: 'English',
    french: 'French', 
    russian: 'Russian',
    spanish: 'Spanish',
    priceRange: 'Price range',
    minimum: 'Minimum',
    maximum: 'Maximum',
    viewProduct: 'View product',
    addToCart: 'Add to cart',
    freeShipping: 'Price includes shipping nationwide',
    moreProducts: 'More products available - for full catalog',
    contactForMore: 'Contact for more details',
    ratedOutOf: 'Rated 5.00 out of 5',
    options: 'options',

    // Downloads page
    freeDownloads: 'Free Downloads',
    downloadDescription: 'Download Breslov books in multiple languages - all books available free to the community',
    search: 'Search',
    searchBooks: 'Search books...',
    category: 'Category',
    rebbeNachman: 'Rebbe Nachman Writings',
    rebbeNathan: 'Rebbe Nathan Writings',
    compilations: 'Compilations',
    downloadLanguage: 'Download Language',
    allLanguages: 'All Languages',
    availableLanguages: 'Available Languages',
    noResultsFound: 'No Results Found',
    tryDifferentSearch: 'Try different search terms',
    importantNote: 'Important Note',
    freeDownloadNote: 'All books are available for free download in the spirit of Breslov - the entire Torah should be free',

    // Checkout page
    checkoutTitle: 'Complete Order',
    shippingDetails: 'Shipping Details',
    fillShippingDetails: 'Please fill in your shipping details',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    zipCode: 'Zip Code',
    orderNotes: 'Order Notes',
    orderNotesPlaceholder: 'Special notes for the order (optional)',
    orderSummary: 'Order Summary',
    items: 'items',
    quantity: 'Qty',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    freeShippingLabel: 'Free',
    subscriberDiscount: 'Subscriber Discount (5%)',
    total: 'Total',
    paymentMethod: 'Payment Method',
    creditCard: 'Credit Card',
    bit: 'Bit',
    paypal: 'PayPal',
    payNow: 'Pay Now',
    processing: 'Processing payment...',
    emptyCart: 'Your cart is empty',
    emptyCartDesc: 'Add products to your cart to proceed to checkout',
    continueShopping: 'Continue Shopping',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'All details are encrypted and secure',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Invalid email address',
    phoneRequired: 'Phone is required',
    phoneInvalid: 'Invalid phone number (05X-XXXXXXX)',
    addressRequired: 'Address is required',
    cityRequired: 'City is required',
    zipCodeRequired: 'Zip code is required',
    spiritualSupport: 'Spiritual Support',
    spiritualSupportDesc: 'Every purchase supports the spiritual mission of spreading Rabbi Nachman of Breslov\'s teachings worldwide',
    shippingPolicy: 'Shipping & Returns Policy',
    freeShippingOver: 'Free shipping on orders over',
    deliveryTime: 'Delivery time: 3-7 business days',
    returnPolicy: 'Returns within 14 days of receiving the product',
    defectivePolicy: 'Defective product - immediate free replacement',

    // Common
    shekel: '₪',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success'
  },
  fr: {
    // Header
    home: 'Accueil',
    store: 'Boutique',
    about: 'À propos',
    contact: 'Contact',
    magazine: 'Magazine',
    join: 'Rejoindre',
    downloads: 'Téléchargements',
    fire: '🔥 Mon Feu',
    discoverCollection: 'Découvrir la Collection',
    booksAvailable: 'Livres Disponibles',

    // Store page
    storeTitle: 'Livres Breslov - Fondation Rabbi Israel',
    storeSubtitle: 'Collection complète des livres de Rabbi Nachman de Breslov et de ses étudiants à prix spéciaux',
    filterBy: 'Filtrer par..',
    freeSearch: 'Recherche libre',
    searchPlaceholder: 'Rechercher...',
    showResults: 'Afficher les résultats de recherche',
    categories: 'Catégories',
    allCategories: 'Toutes les catégories',
    editionType: 'Type d\'édition',
    pocketEditions: 'Éditions de poche',
    luxuryEditions: 'Éditions de luxe',
    completeSets: 'Collections complètes',
    illustratedEditions: 'Éditions illustrées',
    leatherBinding: 'Reliure en cuir',
    languages: 'Langues',
    hebrew: 'Hébreu',
    english: 'Anglais',
    french: 'Français',
    russian: 'Russe',
    spanish: 'Espagnol',
    priceRange: 'Gamme de prix',
    minimum: 'Minimum',
    maximum: 'Maximum',
    viewProduct: 'Voir le produit',
    addToCart: 'Ajouter au panier',
    freeShipping: 'Prix inclut livraison nationale',
    moreProducts: 'Plus de produits disponibles - pour le catalogue complet',
    contactForMore: 'Contactez pour plus de détails',
    ratedOutOf: 'Noté 5.00 sur 5',
    options: 'options',

    // Downloads page
    freeDownloads: 'Téléchargements Gratuits',
    downloadDescription: 'Téléchargez des livres Breslov en plusieurs langues - tous les livres sont disponibles gratuitement pour la communauté',
    search: 'Recherche',
    searchBooks: 'Rechercher des livres...',
    category: 'Catégorie',
    rebbeNachman: 'Écrits de Rebbe Nachman',
    rebbeNathan: 'Écrits de Rebbe Nathan',
    compilations: 'Compilations',
    downloadLanguage: 'Langue de Téléchargement',
    allLanguages: 'Toutes les Langues',
    availableLanguages: 'Langues Disponibles',
    noResultsFound: 'Aucun Résultat Trouvé',
    tryDifferentSearch: 'Essayez des termes de recherche différents',
    importantNote: 'Note Importante',
    freeDownloadNote: 'Tous les livres sont disponibles en téléchargement gratuit dans l\'esprit de Breslov - toute la Torah devrait être gratuite',

    // Checkout page
    checkoutTitle: 'Finaliser la commande',
    shippingDetails: 'Coordonnees de livraison',
    fillShippingDetails: 'Veuillez remplir vos coordonnees de livraison',
    firstName: 'Prenom',
    lastName: 'Nom',
    email: 'Email',
    phone: 'Telephone',
    address: 'Adresse',
    city: 'Ville',
    zipCode: 'Code Postal',
    orderNotes: 'Notes de commande',
    orderNotesPlaceholder: 'Notes speciales pour la commande (optionnel)',
    orderSummary: 'Resume de la commande',
    items: 'articles',
    quantity: 'Qte',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    freeShippingLabel: 'Gratuite',
    subscriberDiscount: 'Remise abonne (5%)',
    total: 'Total',
    paymentMethod: 'Moyen de paiement',
    creditCard: 'Carte bancaire',
    bit: 'Bit',
    paypal: 'PayPal',
    payNow: 'Payer Maintenant',
    processing: 'Traitement du paiement...',
    emptyCart: 'Votre panier est vide',
    emptyCartDesc: 'Ajoutez des produits a votre panier pour passer a la caisse',
    continueShopping: 'Continuer les achats',
    securePayment: 'Paiement securise',
    securePaymentDesc: 'Toutes les informations sont chiffrees et securisees',
    firstNameRequired: 'Le prenom est obligatoire',
    lastNameRequired: 'Le nom est obligatoire',
    emailRequired: 'L\'email est obligatoire',
    emailInvalid: 'Adresse email invalide',
    phoneRequired: 'Le telephone est obligatoire',
    phoneInvalid: 'Numero de telephone invalide (05X-XXXXXXX)',
    addressRequired: 'L\'adresse est obligatoire',
    cityRequired: 'La ville est obligatoire',
    zipCodeRequired: 'Le code postal est obligatoire',
    spiritualSupport: 'Soutien spirituel',
    spiritualSupportDesc: 'Chaque achat soutient la mission spirituelle de diffusion des enseignements de Rabbi Nachman de Breslov dans le monde entier',
    shippingPolicy: 'Politique de livraison et retours',
    freeShippingOver: 'Livraison gratuite pour les commandes de plus de',
    deliveryTime: 'Delai de livraison : 3 a 7 jours ouvrables',
    returnPolicy: 'Retour sous 14 jours apres reception du produit',
    defectivePolicy: 'Produit defectueux - remplacement immediat gratuit',

    // Common
    shekel: '₪',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succes'
  },
  es: {
    // Header
    home: 'Inicio',
    store: 'Tienda',
    about: 'Acerca de',
    contact: 'Contacto',
    magazine: 'Revista',
    join: 'Unirse',
    downloads: 'Descargas',
    fire: '🔥 Mi Fuego',
    discoverCollection: 'Descubrir Colección',
    booksAvailable: 'Libros Disponibles',

    // Store page
    storeTitle: 'Libros Breslov - Fundación Rabino Israel',
    storeSubtitle: 'Colección completa de libros del Rabino Nachman de Breslov y sus estudiantes a precios especiales',
    filterBy: 'Filtrar por..',
    freeSearch: 'Búsqueda libre',
    searchPlaceholder: 'Buscar...',
    showResults: 'Mostrar resultados de búsqueda',
    categories: 'Categorías',
    allCategories: 'Todas las categorías',
    editionType: 'Tipo de edición',
    pocketEditions: 'Ediciones de bolsillo',
    luxuryEditions: 'Ediciones de lujo',
    completeSets: 'Sets completos',
    illustratedEditions: 'Ediciones ilustradas',
    leatherBinding: 'Encuadernación en cuero',
    languages: 'Idiomas',
    hebrew: 'Hebreo',
    english: 'Inglés',
    french: 'Francés',
    russian: 'Ruso',
    spanish: 'Español',
    priceRange: 'Rango de precios',
    minimum: 'Mínimo',
    maximum: 'Máximo',
    viewProduct: 'Ver producto',
    addToCart: 'Añadir al carrito',
    freeShipping: 'Precio incluye envío nacional',
    moreProducts: 'Más productos disponibles - para catálogo completo',
    contactForMore: 'Contactar para más detalles',
    ratedOutOf: 'Calificado 5.00 de 5',
    options: 'opciones',

    // Downloads page
    freeDownloads: 'Descargas Gratuitas',
    downloadDescription: 'Descarga libros Breslov en varios idiomas - todos los libros disponibles gratis para la comunidad',
    search: 'Buscar',
    searchBooks: 'Buscar libros...',
    category: 'Categoria',
    rebbeNachman: 'Escritos del Rebe Najman',
    rebbeNathan: 'Escritos del Rebe Natan',
    compilations: 'Compilaciones',
    downloadLanguage: 'Idioma de Descarga',
    allLanguages: 'Todos los Idiomas',
    availableLanguages: 'Idiomas Disponibles',
    noResultsFound: 'No se Encontraron Resultados',
    tryDifferentSearch: 'Intenta con otros terminos de busqueda',
    importantNote: 'Nota Importante',
    freeDownloadNote: 'Todos los libros estan disponibles para descarga gratuita en el espiritu de Breslov - toda la Tora debe ser gratis',

    // Checkout page
    checkoutTitle: 'Completar pedido',
    shippingDetails: 'Datos de envio',
    fillShippingDetails: 'Por favor complete sus datos de envio',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo electronico',
    phone: 'Telefono',
    address: 'Direccion',
    city: 'Ciudad',
    zipCode: 'Codigo Postal',
    orderNotes: 'Notas del pedido',
    orderNotesPlaceholder: 'Notas especiales para el pedido (opcional)',
    orderSummary: 'Resumen del pedido',
    items: 'articulos',
    quantity: 'Cant.',
    subtotal: 'Subtotal',
    shipping: 'Envio',
    freeShippingLabel: 'Gratis',
    subscriberDiscount: 'Descuento suscriptor (5%)',
    total: 'Total',
    paymentMethod: 'Metodo de pago',
    creditCard: 'Tarjeta de credito',
    bit: 'Bit',
    paypal: 'PayPal',
    payNow: 'Pagar Ahora',
    processing: 'Procesando pago...',
    emptyCart: 'Tu carrito esta vacio',
    emptyCartDesc: 'Agrega productos a tu carrito para proceder al pago',
    continueShopping: 'Seguir comprando',
    securePayment: 'Pago seguro',
    securePaymentDesc: 'Todos los datos estan encriptados y seguros',
    firstNameRequired: 'El nombre es obligatorio',
    lastNameRequired: 'El apellido es obligatorio',
    emailRequired: 'El correo es obligatorio',
    emailInvalid: 'Direccion de correo invalida',
    phoneRequired: 'El telefono es obligatorio',
    phoneInvalid: 'Numero de telefono invalido (05X-XXXXXXX)',
    addressRequired: 'La direccion es obligatoria',
    cityRequired: 'La ciudad es obligatoria',
    zipCodeRequired: 'El codigo postal es obligatorio',
    spiritualSupport: 'Apoyo espiritual',
    spiritualSupportDesc: 'Cada compra apoya la mision espiritual de difundir las ensenanzas de Rabi Najman de Breslov en todo el mundo',
    shippingPolicy: 'Politica de envios y devoluciones',
    freeShippingOver: 'Envio gratuito en pedidos superiores a',
    deliveryTime: 'Tiempo de entrega: 3-7 dias habiles',
    returnPolicy: 'Devolucion dentro de 14 dias de recibido el producto',
    defectivePolicy: 'Producto defectuoso - reemplazo inmediato gratuito',

    // Common
    shekel: '₪',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Exito'
  },
  ru: {
    // Header
    home: 'Главная',
    store: 'Магазин',
    about: 'О нас',
    contact: 'Контакт',
    magazine: 'Журнал',
    join: 'Присоединиться',
    downloads: 'Загрузки',
    fire: '🔥 Мой Огонь',
    discoverCollection: 'Откройте Коллекцию',
    booksAvailable: 'Доступные книги',

    // Store page
    storeTitle: 'Книги Бреслов - Фонд Рабби Израиль',
    storeSubtitle: 'Полная коллекция книг Рабби Нахмана из Бреслов и его учеников по специальным ценам',
    filterBy: 'Фильтровать по..',
    freeSearch: 'Свободный поиск',
    searchPlaceholder: 'Поиск...',
    showResults: 'Показать результаты поиска',
    categories: 'Категории',
    allCategories: 'Все категории',
    editionType: 'Тип издания',
    pocketEditions: 'Карманные издания',
    luxuryEditions: 'Люксовые издания',
    completeSets: 'Полные наборы',
    illustratedEditions: 'Иллюстрированные издания',
    leatherBinding: 'Кожаный переплет',
    languages: 'Языки',
    hebrew: 'Иврит',
    english: 'Английский',
    french: 'Французский',
    russian: 'Русский',
    spanish: 'Испанский',
    priceRange: 'Диапазон цен',
    minimum: 'Минимум',
    maximum: 'Максимум',
    viewProduct: 'Посмотреть товар',
    addToCart: 'Добавить в корзину',
    freeShipping: 'Цена включает доставку по стране',
    moreProducts: 'Больше товаров доступно - для полного каталога',
    contactForMore: 'Свяжитесь для получения подробностей',
    ratedOutOf: 'Рейтинг 5.00 из 5',
    options: 'вариантов',

    // Downloads page
    freeDownloads: 'Бесплатные Загрузки',
    downloadDescription: 'Скачайте книги Бреслов на разных языках - все книги бесплатно для сообщества',
    search: 'Поиск',
    searchBooks: 'Поиск книг...',
    category: 'Категория',
    rebbeNachman: 'Писания Ребе Нахмана',
    rebbeNathan: 'Писания Ребе Натана',
    compilations: 'Сборники',
    downloadLanguage: 'Язык Загрузки',
    allLanguages: 'Все Языки',
    availableLanguages: 'Доступные Языки',
    noResultsFound: 'Результаты Не Найдены',
    tryDifferentSearch: 'Попробуйте другие поисковые запросы',
    importantNote: 'Важное Примечание',
    freeDownloadNote: 'Все книги доступны для бесплатного скачивания в духе Бреслов - вся Тора должна быть бесплатной',

    // Checkout page
    checkoutTitle: 'Оформление заказа',
    shippingDetails: 'Данные доставки',
    fillShippingDetails: 'Пожалуйста, заполните данные доставки',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Электронная почта',
    phone: 'Телефон',
    address: 'Адрес',
    city: 'Город',
    zipCode: 'Почтовый индекс',
    orderNotes: 'Примечания к заказу',
    orderNotesPlaceholder: 'Особые примечания к заказу (необязательно)',
    orderSummary: 'Сводка заказа',
    items: 'товаров',
    quantity: 'Кол-во',
    subtotal: 'Подитог',
    shipping: 'Доставка',
    freeShippingLabel: 'Бесплатно',
    subscriberDiscount: 'Скидка подписчика (5%)',
    total: 'Итого',
    paymentMethod: 'Способ оплаты',
    creditCard: 'Кредитная карта',
    bit: 'Бит',
    paypal: 'PayPal',
    payNow: 'Оплатить сейчас',
    processing: 'Обработка платежа...',
    emptyCart: 'Ваша корзина пуста',
    emptyCartDesc: 'Добавьте товары в корзину, чтобы перейти к оформлению заказа',
    continueShopping: 'Продолжить покупки',
    securePayment: 'Безопасный платеж',
    securePaymentDesc: 'Все данные зашифрованы и защищены',
    firstNameRequired: 'Имя обязательно',
    lastNameRequired: 'Фамилия обязательна',
    emailRequired: 'Электронная почта обязательна',
    emailInvalid: 'Неверный адрес электронной почты',
    phoneRequired: 'Телефон обязателен',
    phoneInvalid: 'Неверный номер телефона (05X-XXXXXXX)',
    addressRequired: 'Адрес обязателен',
    cityRequired: 'Город обязателен',
    zipCodeRequired: 'Почтовый индекс обязателен',
    spiritualSupport: 'Духовная поддержка',
    spiritualSupportDesc: 'Каждая покупка поддерживает духовную миссию распространения учения Рабби Нахмана из Бреслова по всему миру',
    shippingPolicy: 'Политика доставки и возвратов',
    freeShippingOver: 'Бесплатная доставка при заказе от',
    deliveryTime: 'Срок доставки: 3-7 рабочих дней',
    returnPolicy: 'Возврат в течение 14 дней после получения товара',
    defectivePolicy: 'Дефектный товар - бесплатная немедленная замена',

    // Common
    shekel: '₪',
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успех'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState('he');

  useEffect(() => {
    const saved = localStorage.getItem('site-language');
    if (saved && saved in translations) {
      setCurrentLanguage(saved);
      document.dir = saved === 'he' ? 'rtl' : 'ltr';
    } else {
      document.dir = 'he' === 'he' ? 'rtl' : 'ltr';
    }
  }, []);

  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('site-language', language);
    document.dir = language === 'he' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    const currentTranslations = translations[currentLanguage as keyof typeof translations] || translations.he;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}